frontend/app/scripts/tubemap.js

Hello, I found a bug that if the nodeId is assigned as `0` by `generateNodeMap`, then it cannot distinguish `x = 0` or `x = -0` by `x >= 0` in `currentNodeIsForward` variable. It caused the unexpected output in an inversion region.

Fix: currentNodeIsForward 

---

backend/app.js
backend/package.json

This allows us not to get crosstalk between requests if multiple
requests are having their chunks computed at once.
This will fix #32.

Put temporary files in directories

---

backend/app.js
backend/package.json
frontend/app/index.html
frontend/app/scripts/main.js

This includes a couple patches on top of #51 to make it work right on my installation.
- I added the "websockets" module to the package.json. @tanessav When you depend on a new module, you need to put it in the package.json so it will get installed; `npm install --save whatever-module` in the backend or frontend directory is the right way to do this.
- I changed the frontend error detection to check if the graph was sent, rather than if an error message was sent. Sometimes vg sends warnings to standard error (in my case, messages about my xg index being in an old and slow format) but works anyway. This way, you can still see the graph even when there are warnings.
- I changed innerHTML to innerText, because if you put raw text in innerHTML it gets parsed as HTML as part of the page, which …

Error improvements

---

src/util/tubemap.js

This commit fixes the issues with the displaying of reads described in #78 .

Deselecting "Show sequence reads" breaks IVG completely

---

README.md
package.json

Without this, we can't see what's going on when the frontend throws anything.
With it, we get nice stack traces rendered by React into the page for us, when using `npm run start`:
This will fix #107.

Configure and describe dev mode with the React dev server

---

package.json
src/App.js
src/components/CustomizationAccordion.js
src/components/DataPositionFormRow.js
src/components/ExampleSelectButtons.js
src/components/FileUploadFormRow.js
src/components/HeaderForm.js
src/components/MountedDataFormRow.js
src/components/RadioRow.js
src/components/TubeMap.js
src/components/TubeMapContainer.js
src/server.js

This fixes #114.
The underlying problem was that a prop that was supposed to be filled in wasn't, so I pulled in `prop-types` so we should now get browser console complaints if a prop isn't set when it should be.

Add prop types and pass backend URL to file upload form

---

deploy.md
src/App.js
src/components/FileUploadFormRow.js
src/components/HeaderForm.js
src/components/TubeMapContainer.js
src/end-to-end.test.js
src/server.js
src/setupProxy.js

To get the React dev server to proxy the web sockets through properly, I've had to put the API on its own path separate from the static files. But with that and a manual proxy configuration, the websockets are back to working.

Move API to `/api/v0` and proxy web sockets

---

.gitignore
package.json
src/App.css
src/components/FileUploadFormRow.js
src/components/MountedDataFormRow.js
src/components/SelectionDropdown.js

Closes #115. This replaces a bunch of dropdowns with a custom searchable Select component from `react-select`. 
The UI will be slower with thousands of options since it's not using the native \<select\>\<option\> tags, but hopefully the search would help with that.

Add search to dropdowns

---

src/components/TubeMapContainer.js
src/util/tubemap.js

This will fix #133 by going back to the old method of flipping paths that visit all nodes in reverse, for layout purposes. The tick generator can now tell when the ruler track has been flipped like this, and unflip it for tick generation.
I still think we need to rethink a lot of the orientation support to be able to know if it is really correct. But this will make the Cactus graph example look nice without reintroducing #88.

Bring back isCompletelyReverse for layout, and consult it when generating ticks

---

src/server.js

This will fix #150 by making sure that `setImmediate` is always available to Express in the server, even when we are loading the server inside a `jsdom` Jest environment and Jest is trying to hide it from us.
In the long term, we want to work out a better way to do end-to-end tests (maybe by having control of our own frontend-and-backend tests that know how to start a server and test the frontend pieces against it, instead of just gluing the server into the react-scripts frontend tests). We also want to be able to test the frontend components alone, by having a design where it's easy to mock API responses. But we aren't doing that refactor right now just because Jest updated.

Fix #150 by making sure server has a setImmediate

---

src/components/HeaderForm.js

This solves #166 by setting region to 'none' whenever a data type is switched

Clear region whenever switching between data types

---

src/util/tubemap.js

When most paths go through a node in reverse, tubemap will switch it to make the graph visually better. However, the sequence  of the switched node was incorrect (reverse instead of reverse-complement). This fixes that, now the reverse-complemented sequence is shown on "switched" nodes.

Reverse complement sequence when switching nodes

---

src/components/HeaderForm.js

It looks like the default selection for the "region" file is not initialized properly after startup when switching to mounted data. It looks for the BED file from the example, can't find it in the mounted data folder, and raises an error. 
I've made it so that the value of the default BED file is re-initialized (to "none") when switching data sources. I don't think we want to keep the previous selection if we're changing data sources. 
I've also added a test to only read a BED file if there is a selected BED file (i.e. not *none*)

Fix an error when no regions are selected for mount data

---

src/components/CopyLink.js

CopyLink does not work if HTTPS is used for the the app. The protocol is missing.

CopyLink: Use window.location.origin instead of window.location.host

---

package-lock.json
package.json
src/App.js
src/Types.ts
src/components/CustomizationAccordion.js
src/components/ExampleSelectButtons.js
src/components/RadioRow.js
src/components/TubeMapContainer.js
src/config.json
src/util/tubemap.js

Allow different selections of colors for reads and haplotypes. 
- Changed config field to store color variables using array and object, as opposed to individual fields
- Uses colors[0] to store haplotype colors, subsequent slots are for reads
- Colors array also stores colorbyMappingQuality for individual entries
- currently updates all of them to the same value

Different Colors for Haplotype and GAM Files

---

src/components/ExampleSelectButtons.js
src/components/TubeMapContainer.js
src/enums.js
src/util/demo-data.js
src/util/tubemap.js

This should improve  the situation in #240. There we had this:
You can see that a lot of reads go through this node in reverse, and they are interleaved with the reads that bypass it.
Now I can get this:
The node is automatically flipped because it is mostly visited in reverse, and I fixed some bookkeeping that would break our signed-index visit representation for the 0th node.
The node's tooltip also explains that the node is being flipped around for display.
I think we can still get the problems in #240, which looks like it is really caused by interleaving reads that need to visit a node in reverse with reads that need to bypass that node, and also by each read that needs to visit a node in reverse needing its own dedicated X-axis lane on either side of the node, but us not having a way …

Improve bad read layout

---

src/components/CustomizationAccordion.js
src/components/RadioRow.js
src/components/TrackSettings.js
src/components/TrackSettingsButton.js

This plugs in the track settings forms and gets rid of the reverse haplotype color setting.
I had to change the track settings dialogs to modals because of https://github.com/yjose/reactjs-popup/issues/334, and they don't look as good like that, because then the position is ignored and they just end up in the center of the screen.

Plug in track settings

---

package-lock.json
package.json

This PR just adds `jest-compact-reporter` as a reporter in addition to the default reporter.
It will cause `npm run test` to output Jest's default report followed by a summary of which tests passed and failed.

Install a compact test reporter for jest

---

package.json

This fixes:
```
npm run test -- src/components/HelpButton.test.js
```
It adds a no-op option (setting `--watchAll` to its default) to stop `--reporters` eating the positional arguments.
You can still override it the normal way, because the last option wins:
```
npm run test -- --watchAll=false src/components/HelpButton.test.js
```
I think this will close https://github.com/vgteam/sequenceTubeMap/pull/263 because now we can just use `npm run test` all the time and always have the nice summary reporter, and we won't need a separate `npm run ci:test`.

Add --seed to terminate --reporters parsing

---

src/App.js
src/components/TubeMapContainer.js

Having `tubemap` functions in `App.js` makes it easy to introduce errors when calling imperative functions on the tubemap module. It's better to have all those confined to `TubeMapContainer`.
This PR removes all `tubemap` functions from `App.js` and puts them into `TubeMapContainer.js`. Instead of being called when `App` updates, they will be called when `TubeMapContainer` updates. This allows us to check `isLoading` and prevent calling tubemap functions before the track has loaded.
The state for `visOptions` will continue to be held in the state of `App` so it can be modified by other parts of the program, and `visOptions` will be passed down as a prop to `TubeMapContainer`.
This should fix the issue where changing colors while the tube map is loading crashes the web page …

Move tubmap function calls into TubeMapContainer

---

src/components/TrackAddButton.js
src/components/TrackList.js
src/components/TrackListItem.js
src/components/TrackPicker.demo.js
src/components/TrackPicker.js
src/components/TrackPicker.test.js
src/components/TrackSettingsButton.js

I decided to put the button component directly into TrackPicker, it made sense to me to skip a generic button component.
- TrackPicker calls onChange when TrackPickerDisplay does, perhaps it might be better to do this when the user exits the popup?
- Changed TrackSettings to exit upon clicking outside the popup, while the TrackPicker popup only exits upon clicking the X button
- TrackListItem now only takes up a fixed # of pixels in width, removing white space in TrackPicker

Merge TrackPicker

---

package-lock.json
package.json
src/common.mjs
src/components/HeaderForm.js
src/end-to-end.test.js
src/server.mjs

This uses cheating and hackery to allow files with the extension ".mjs" to be importable by both the client *and* the server code. As long as they are written using import, but never try to touch import.meta or import assertions or require or the other CommonJS things like __dirname, they will be acceptable both to Node on the server side and to Babel on the client side and to Jest during the tests.
I am using this to centralize the parsing/unparsing of region strings, so we can be using the same code throughout and thus not get into trouble with colons in the contig being supported in some places but not in others.
This will fix #284.

Support colons in contigs and polyglot-ify to allow shared client-server imports

---

.devcontainer/devcontainer.json
src/App.js

This sets up a devcontainer configuration so that the tube map can work in [Github Codespaces](https://github.com/features/codespaces). This will let people develop on the tube map using a potato, provided the potato can run a web browser and log in to Github. Codespaces also integrate with a local VS Code editor.
It includes some base64-encoded Bash glue to set the right environment variables to make the Webpack dev server, as configured by Create React App, happy behind the proxy domains that Github creates to achieve a "port forward" into a container with Github login access control in front of it. I couldn't figure out how to get the glue through the container build process without encoding it, except for maybe making a separate Dockerfile for the devcontainer.

Add devcontainer config to support Codespaces

---

src/components/CopyLink.js
src/components/HeaderForm.js
src/components/TubeMap.js
src/util/tubemap.js

This changes GAM layout so that multiple tracks are laid out separately in separate passes, one below the other.
It looks like this, where I have an orange GAM and then a purple GAM. There's a 1-read-high margin between/above GAM tracks in each node when multiple GAM tracks are added.
This PR also includes some fixes for deserializing the link to view URLs and for tunring mapping quality coloring on and off, since I ran into related bugs when trying to use the view links to test this.
This will fix #216.

Split multiple GAM tracks vertically

---

src/components/TubeMapContainer.js
src/end-to-end.test.js
src/server.mjs

This will fix #312 by ordering the GAMs based on the naming convention used by vg chunk [here](https://github.com/vgteam/vg/blob/855294e5e0178b96e22753fc6ce2ae71e37a5726/src/subcommand/chunk_main.cpp#L937).
We are also now sending GAMs back as an array instead of an object, because the keys we were using were internal temp file names and not the real GAM track names anyway.

Parse vg chunk GAM names and send back as an ordered array

---

src/App.css
src/components/TubeMapContainer.js
src/util/tubemap.js

This will fix #320. Now scrolling on the visualization can't scroll the page but only zooms the visualization. Also, we can pan both vertically and horizontally (again?). And the visualization stays full height even if you zoom out and the picture itself is smaller, preventing zooming from reflowing the whole page.

Better scrolling and panning for tall graphs

---

src/util/tubemap.js
src/util/tubemap.test.js

Node coverage stats deletions

---

README.md
docker/config.json
exampleData/chunk-ref-1-20/tracks.json
scripts/prepare_local_chunk.sh
src/components/TubeMapContainer.js
src/server.mjs
src/util/tubemap.js

This should fix the problem with #335 where we couldn't parse the track JSON.
It also adds a new script to try and make making a chunk from a pre-made subgraph easier, and it makes the chunk scripts output the BED lines you would want.

Fix track JSON load, make sure chunk ref path is first, and add script to help make a chunk from a graph

---

scripts/prepare_chunks.sh
scripts/prepare_local_chunk.sh

Instead of a space-separated list, we can just pass the same option multiple times.

Do multiple node highlighting with multiple -n options

---

scripts/prepare_chunks.sh
scripts/prepare_local_chunk.sh

This should let us once again run the chunk preparation scripts even when we aren't standing in the root of the repository.

Make chunk scripts find config.json relative to themselves

---

exampleData/cactus_mixed_chunks.bed
src/common.mjs
src/components/HeaderForm.js
src/components/RegionInput.js
src/components/RegionInput.test.js
src/server.mjs

- Chunk metadata from the internet is no longer downloaded until region selection
- GetChunkedData now confirms tracks from a bedURL as user might've pressed Go before tracks are fetched
- Closes #353 
Summary of the current process for bedURLs:
- Upon receiving a bedURL, only the bed file is fetched and bedinfo such as regions are returned 
- Upon selection of a bed region, the respective tracks.json file for that chunk is fetched and tracks are loaded into the track picker if applicable
- Upon receiving a request to getChunkedData, if a bedURL is present, the tracks.json file is re-fetched(if necessary) and used instead of the given tracks from the request in case the user hit the GO button before tracks were loaded into the track picker
- getChunkedPath is called when a bed file is …

Lazy Bed Regions Download

---

src/components/RegionInput.js
src/end-to-end.test.js

Display Region Description as Label and Tooltip

---

src/components/HeaderForm.js
src/components/RegionInput.js
src/end-to-end.test.js

Use label system to display both path with region and description while ignoring description upon onChange
Closes #362

Improve Region Dropdown Selections

---

src/components/HeaderForm.js
src/components/RegionInput.js
src/components/RegionInput.test.js
src/end-to-end.test.js

Puts Description, if available, as text below Go button.
Closes #378

Implement highlightable description

---

src/util/tubemap.js

Added read path information to read info dialog

---

package-lock.json
package.json
patches/@bjorn3+browser_wasi_shim+0.2.17.patch
src/APIInterface.mjs
src/App.js
src/GBZBaseAPI.mjs
src/GBZBaseAPI.test.js
src/ServerAPI.mjs
src/components/HeaderForm.js
src/components/TubeMapContainer.js
src/setupTests.js

This pulls in a dependency on an NPM module with the WASM blobs for doing API requests locally, and also adds a skeleton of an API implementation and the beginning of tests for it.
I still can't actually load the WASM blob; I think I am going to need to swap out some code between running on Jest and building with Webpack somehow, to get the bytes.

Add sketch of WASM integration

---

scripts/prepare_chunks.sh
scripts/prepare_local_chunk.sh
src/components/HeaderForm.js
src/components/RegionInput.js
src/components/RegionInput.test.js

This attaches the left-right button stuff to the region description stuff so that the description updates when you go left and right.
It also includes chunk generation script changes to let you set palettes from the command line.
To do the demo today with the Lancet data I used this bit of Bash:
```
rm -f exampleData/lancet_regions.bed
for REGION_NAME in $((cd /Users/anovak/Downloads/STM_DataShare_Nov07_2023/giraffe_alignments/ && ls normal.*.sorted.gam) | sed 's/normal\.//g' | sed 's/\.sorted\.gam//g') ; do
CONTIG="$(echo "${REGION_NAME}" | cut -f1 -d'_')"
COORD_START="$(echo "${REGION_NAME}" | cut -f2 -d'_')"
COORD_END="$(echo "${REGION_NAME}" | cut -f3 -d'_')"
(cd exampleData && rm -Rf "lancet_regions-${REGION_NAME}" && ../scripts/prepare_local_chunk.sh -x …
```

Left-right button and region description integration

---

src/components/ExampleSelectButtons.js
src/components/TubeMapContainer.js
src/enums.js
src/util/demo-data.js
src/util/tubemap.js

Segments cycling on the first node had strange interactions since segments classified as "outgoing"(if its pathIndex == 0) had different methods of sorting.
Changes are made to how reads are placed outside of nodes when a cycle is detected, and inside of nodes when reads have the same source and destination Node.
- A new tiebreaker is placed in sortByGoingTo for reads that start and end in the same node. Now they're placed based on the endmost node they were placed in, working its way back if there are no y values. Since these reads start and end in the same node, this should start the reads(in the first node) in the same order as the other nodes.
- Segments outside of nodes now detects cycles, defined as the previous and next segments are in the node and going in the same direction. …

Improve Read Cycle Layout

---

src/util/tubemap.js

An offset designated for each node is used when generating vertical components of tracks. This leads to vertical transitions being determined by the order of the input tracks.
https://github.com/vgteam/sequenceTubeMap/blob/f4ab3c27dd53fc0ce0627d6a4885269378eb75ba/src/util/tubemap.js#L2942-L2953
https://github.com/vgteam/sequenceTubeMap/blob/f4ab3c27dd53fc0ce0627d6a4885269378eb75ba/src/util/tubemap.js#L3010
Tracks are now sorted based on how their horizontal components are ordered before generating vertical rectangles, allowing the offsets to work in a more predictable manner.
Closes #395

Fix Out of Order Veritcal Transitions

---

public/help/help.md

Doc link to view url params

---

README.md
scripts/prepare_local_chunk.sh

`prepare_local_chunk.sh`  now converts `.gaf` files into gam files before processing them.
Closes #355.

GFA Documentation + GAF in prepare_local_chunk

---

src/components/HeaderForm.js

This makes the left and right buttons work again when BED file is "none".

Formalize system of using 'none' in bedFile to fix left and right buttons without BED

---

src/util/tubemap.js

Sometimes tracks don't have enough space to make a smooth transition from node to node. This PR creates extra space between nodes, taking into account the maximum difference in y values between nodes given any track. 
snp1kg-BRCA1
Before:
After:
chr1_15608265_15608765
Before:
After:

Extra Space Between Nodes

---

jesthtmlreporter.config.json
package-lock.json
package.json

`npm run test` now includes an HTML file in the test_report directory, showing test results more clearly.

Add HTML Test Reporter

---

src/server.mjs

Use relative paths in link to view

---

scripts/prepare_lancet_output.sh
scripts/prepare_local_chunk.sh
src/components/CopyLink.js
src/server.mjs
src/util/tubemap.js

This fixes #427 sort of by making a BED that explains what variant is supposed to be seen.
I ran it like this:
```
cd ~/workspace/sequenceTubeMap
mkdir -p webhost
cd webhost
~/workspace/sequenceTubeMap/scripts/prepare_lancet_output.sh ~/Downloads/STM_DataShare_Nov07_2023\ 2/ ./lancet_2023-11-07
cd lancet_2023-11-07
python3 -m http.server
```
Then I could put `http://[::]:8000/index.bed` into my local tube map as the BED file and browse the data.
But, I think the data provided is not exactly what I really want to look at. It looks liek the called tumor variants are not actually *in* the graphs. For example, at `chr1:38506973-38506974` I am suppsoed to see a `Tumor-specific CTGGAATCCAGCAGCCCAGACTTCCACATCATAATTTTCTGGGGCAATGGTTTTCAAACTTCACTGTACG -> C DEL variant`. But the graph doesn't show a …

Add a script that can batch import and explain Lancet data in the November format

---

src/util/tubemap.js

Modified sorting logic to sort no-node reads

---

scripts/prepare_local_chunk.sh

I want the Lancet-side driver script to be able to make BED files that won't break if you change the absolute path to the tube map repo. So this lets you feed a base path (the directory where the BED will live) to the script.

Add relative path support to local chunk script for Lancet integration

---

src/util/tubemap.js

This fixes a problem where you can upload a graph with haplotype-sense paths in it and crash the front-end with an unrecognized "haplo" track type.

Always internally use "haplotype" and never "haplo" to avoid mismatches

---

scripts/prepare_vg.sh
src/errors.mjs
src/scripts.test.js
src/server.mjs
src/util/tubemap.js
src/vg.mjs

This should fix #472 in two ways.
We no longer make one giant string of all the path names (though we do call `res.json()` with one giant object), and we now have some error handlers in the callbacks in that call (but not others) that catch errors and call `next()`.

Parse path name lines live and festoon callbacks with error handling

---

src/util/tubemap.js

This explains the D3 bounds setting a bit more and makes it so we can pan down enough to not make D3 push the image out of the bounds we set on the SVG.

Fix out-of-bounds image downloads
