.gitignore
README.md
frontend/app/scripts/main.js
frontend/config.default.json
frontend/gulpfile.js
frontend/package.json

Now setting the BACKEND_URL won't require editing files under source control.
Instead, you set all your local build settings in a config.json, with the
defaults in a config.default.json.

Adopt a 2-layer way to do the configs

---

backend/app.js
frontend/app/index.html
frontend/app/scripts/main.js
frontend/app/styles/main.css

This fixes #47. The reload button reloads the lists of files in the dropdowns without refreshing the page. To be fixed: Selections in the dropdowns being refreshed are not preserved.

Add Reload Data Files Buttons

---

backend/app.js
frontend/app/index.html
frontend/app/scripts/main.js

This fixes #39. When the user enters an out of bound input, an error message generated from vg will be displayed instead of the Tube Map.

Handle out of bound user inputs #39

---

frontend/app/index.html
frontend/app/scripts/main.js
frontend/bower.json

This fixes #34. When the user updates the browser, the checkboxes go back to their default state.

 Update checkbox states across page refreshes #34

---

.gitignore
frontend/app/index.html
frontend/app/scripts/main.js
frontend/app/scripts/tubemap.js
frontend/gulpfile.js

Fix #9 **More Zooming**
* Add zoom in and zoom out buttons
* If the whole image is visible and you are in the last level of zoom out, and press zoom out button the image expands and centralize.
* Change ScaleExtent from 5 to 8
* Export zoom object from tubeMap.js to get access in main.js

Zooming Functionalities 

---

src/server.js

Port 3000 is busy on Courtyard so I have to run on a different port. This makes changing the port slightly easier.

Make server port a constant so it can be changed

---

src/util/tubemap.js

This makes node name orientation be handled via functions, instead of strign
indexing and substr.
It also makes node index orientation be removed (with Math.abs) everywhere an
indexSequence is read.
It partially reverts f61437b7ea56ca678b36f3736a4357f2480ea9c0, and instead of
making indexSequence always be positive numbers, we keep tracking orientation
through the index sequences and instead fix `drawRuler` and similar functions
to pull out the non-oriented node ID when looking for the node. This should fix
up #93 in a different way.

Regularize orientation

---

package-lock.json
package.json
src/App.js
src/App.test.js
src/Types.ts
src/components/BedRegionsFormRow.js
src/components/CopyLink.js
src/components/DataPositionFormRow.js
src/components/HeaderForm.js
src/components/TubeMapContainer.js
src/config.json
src/end-to-end.test.js
src/server.js

- **Adds a 'Copy Link' button that allows the user to link to the current view**
- Refactor the fetchParams and similar data types into a viewTarget 
- Minor fixes in errors and button styling
- E2E tests for copy button before and after hitting 'Go'
- Manually tested on examples (small and cactus), mounted files

Add link to the current view

---

src/server.js

Previously, if an error response containing HTML was received, an error about being unable to parse HTML would appear. With this PR, it will display the message 'Something about this request has caused a server error: ', along with the actual error response. This fixes a portion of Issue #157.
Before:
This PR:

Add generic 500 error message and fix error parsing HTML for error responses

---

README.md
package-lock.json
package.json
src/components/HeaderForm.js
src/components/MountedDataFormRow.js
src/components/SelectionDropdown.js
src/end-to-end.test.js

Fix mounted files

---

src/components/CopyLink.js
src/end-to-end.test.js

This is on top of #184 and will fix #186.

Support protocol in copied links

---

src/components/Footer.js

@ducku pointed out that I added some new warnings when I added the footer component; this fixes that.

Fix new warings from footer

---

src/components/TrackTypeDropdown.demo.js
src/components/TrackTypeDropdown.js
src/components/TrackTypeDropdown.test.js

Component for #221 to create a Track Type Dropdown. Includes a demo file and tests as well.

Implement TrackTypeDropdown

---

src/components/TrackFilePicker.demo.js
src/components/TrackFilePicker.js
src/components/TrackFilePicker.test.js

File dropdown selection component alongside tests and demo
- would like to get redux to work 
- need to change file submission endpoints to get file upload working

Track file picker

---

src/components/TrackDeleteButton.demo.js
src/components/TrackDeleteButton.js
src/components/TrackDeleteButton.test.js

Work in progress for track delete button

adding track delete button files

---

src/components/TrackSettingsButton.js
src/components/TrackSettingsButton.test.js

Change appearance of track settings button and make popup controlled

---

src/App.css
src/components/TrackDeleteButton.js
src/components/TrackFilePicker.test.js
src/components/TrackListItem.demo.js
src/components/TrackListItem.js
src/components/TrackListItem.test.js
src/components/TrackSettingsButton.js
src/components/TrackTypeDropdown.js
src/components/TrackTypeDropdown.test.js

TrackListItem component combining:
- TrackFilePicker
- TrackTypeDropdown
- TrackDeleteButton
- TrackSettingsButton
Changing the track type clears the file field, preventing invalid track type, file type combinations.
Styling may still need a bit of work.

Track list item

---

src/App.css
src/components/TrackSettingsButton.js
src/components/TrackSettingsButton.test.js

#250 Made some changes to popup of track settings button.

Change track settings popup

---

package-lock.json
src/components/RadioRow.js
src/components/TrackDeleteButton.js
src/components/TrackFilePicker.js
src/components/TrackList.demo.js
src/components/TrackList.js
src/components/TrackList.test.js
src/components/TrackListItem.demo.js
src/components/TrackListItem.js
src/components/TrackListItem.test.js
src/components/TrackSettingsButton.js
src/components/TrackTypeDropdown.js

- Add keys to radio row component
- Attach trackID to end of the testing tag to select specific items in the tracklist
- Rework TrackListItem to no longer rely on an event handler reference
- Now keep a local version of uncommitted differences 
- Implement TrackList

Track list

---

package-lock.json
package.json
src/App.css
src/App.js
src/Types.ts
src/components/ColorPicker.demo.js
src/components/ColorPicker.js
src/components/TrackList.demo.js
src/components/TrackList.js
src/components/TrackList.test.js
src/components/TrackListItem.demo.js
src/components/TrackListItem.js
src/components/TrackListItem.test.js
src/components/TrackSettings.demo.js
src/components/TrackSettings.js
src/components/TrackSettings.test.js
src/components/TrackSettingsButton.demo.js
src/components/TrackSettingsButton.test.js
src/config.json
src/util/tubemap.js

- Implement ColorPicker component that uses React-Color to pick a single color
- Integrate ColorPicker into TrackSettings
- Allow tubemap to take a React-Color object in addition to a set of colors

Single color gams/haplotype

---

src/components/RegionInput.js
src/server.js

Handle commas in coordinates #259

Handle commas in coordinates

---

src/components/ColorPicker.js
src/components/TrackAddButton.js
src/components/TrackFilePicker.js
src/components/TrackList.js
src/components/TrackList.test.js
src/components/TrackListItem.js
src/components/TrackListItem.test.js
src/components/TrackPickerDisplay.demo.js
src/components/TrackPickerDisplay.js
src/components/TrackPickerDisplay.test.js
src/components/TrackSettings.js
src/components/TrackTypeDropdown.js
src/config.json

Issues #227 and #228
Implement TrackListDisplay, with functionality for add and delete buttons. 
- Local state of Track Items is kept
- Changes are pushed when all files have been selected
- Add and delete buttons modify the track list respectively

Implement TrackListDisplay

---

src/components/RegionInput.js

fixed region field label hovering over other elements

---

src/components/HelpButton.js
src/components/PopUpTrackText.js
src/components/PopupDialog.js
src/components/TrackSettingsButton.js

new popup dialog component

---

docker/Dockerfile
docker/README.md
docker/config.json

This is how I usually use the tubemap, on servers or locally. 
It works with the latest commit, but we might want to have a system of tag/version to tag the docker container too.
I've pushed an image on https://quay.io/repository/jmonlong/sequencetubemap for now.

Documentation on how to make and use docker container

---

src/components/CopyLink.js

Fixes #281

---

src/util/tubemap.js

Also fixes determination for when to use the margin.

Sort tracks by number ID and make margin bigger

---

src/components/TrackSettings.js
src/config.json
src/util/tubemap.js

Highlight reference paths

---

exampleData/chunk-ref-1-20/tracks.json
package-lock.json
package.json
scripts/prepare_chunks.sh
src/config.json
src/end-to-end.test.js
src/server.mjs
src/util/tubemap.js

Color palette preferences presets

---

README.md
scripts/prepare_chunks.sh
scripts/prepare_local_chunk.sh
src/components/TubeMap.js
src/components/TubeMapContainer.js
src/server.mjs
src/util/tubemap.js

Color nodes

---

src/server.mjs

- Storing of ETags from fetch requests, preventing fetching files that have not been updated and are already on disk

prevent repeated fetch of downloaded files

---

src/components/HeaderForm.js

Fix failed prop type error

---

docker/config.json
src/App.js
src/Types.ts
src/config.json
src/end-to-end.test.js

Remove references to dataPath

---

src/util/tubemap.js
src/util/tubemap.test.js

Resolved extra horizontal space between nodes with a coordinate bar break

---

src/util/tubemap.js

Aligned first and last coordinate

---

src/components/HeaderForm.js
src/config.json

New data dropdown option for Lancet example
